# coding: utf-8

from __future__ import absolute_import

# import IesClient
from huaweicloudsdkies.v1.ies_client import IesClient
from huaweicloudsdkies.v1.ies_async_client import IesAsyncClient
# import models into sdk package
from huaweicloudsdkies.v1.model.charge_mode import ChargeMode
from huaweicloudsdkies.v1.model.compute_spec import ComputeSpec
from huaweicloudsdkies.v1.model.condition import Condition
from huaweicloudsdkies.v1.model.create_edge_site import CreateEdgeSite
from huaweicloudsdkies.v1.model.create_edge_site_request import CreateEdgeSiteRequest
from huaweicloudsdkies.v1.model.create_edge_site_request_body import CreateEdgeSiteRequestBody
from huaweicloudsdkies.v1.model.create_edge_site_response import CreateEdgeSiteResponse
from huaweicloudsdkies.v1.model.create_location import CreateLocation
from huaweicloudsdkies.v1.model.delete_edge_site_request import DeleteEdgeSiteRequest
from huaweicloudsdkies.v1.model.delete_edge_site_response import DeleteEdgeSiteResponse
from huaweicloudsdkies.v1.model.edge_site_detail import EdgeSiteDetail
from huaweicloudsdkies.v1.model.list_edge_site_metrics_request import ListEdgeSiteMetricsRequest
from huaweicloudsdkies.v1.model.list_edge_site_metrics_response import ListEdgeSiteMetricsResponse
from huaweicloudsdkies.v1.model.list_edge_sites_request import ListEdgeSitesRequest
from huaweicloudsdkies.v1.model.list_edge_sites_response import ListEdgeSitesResponse
from huaweicloudsdkies.v1.model.list_quotas_request import ListQuotasRequest
from huaweicloudsdkies.v1.model.list_quotas_response import ListQuotasResponse
from huaweicloudsdkies.v1.model.list_racks_request import ListRacksRequest
from huaweicloudsdkies.v1.model.list_racks_response import ListRacksResponse
from huaweicloudsdkies.v1.model.list_storage_pools_request import ListStoragePoolsRequest
from huaweicloudsdkies.v1.model.list_storage_pools_response import ListStoragePoolsResponse
from huaweicloudsdkies.v1.model.list_supported_regions_request import ListSupportedRegionsRequest
from huaweicloudsdkies.v1.model.list_supported_regions_response import ListSupportedRegionsResponse
from huaweicloudsdkies.v1.model.location_detail import LocationDetail
from huaweicloudsdkies.v1.model.market_options import MarketOptions
from huaweicloudsdkies.v1.model.metric_data_detail import MetricDataDetail
from huaweicloudsdkies.v1.model.metric_data_detail_dimension import MetricDataDetailDimension
from huaweicloudsdkies.v1.model.page_info import PageInfo
from huaweicloudsdkies.v1.model.pay_mode import PayMode
from huaweicloudsdkies.v1.model.prepaid_options import PrepaidOptions
from huaweicloudsdkies.v1.model.quota_detail import QuotaDetail
from huaweicloudsdkies.v1.model.quota_resources import QuotaResources
from huaweicloudsdkies.v1.model.rack import Rack
from huaweicloudsdkies.v1.model.rack_info import RackInfo
from huaweicloudsdkies.v1.model.rack_status import RackStatus
from huaweicloudsdkies.v1.model.region_detail import RegionDetail
from huaweicloudsdkies.v1.model.show_edge_site_request import ShowEdgeSiteRequest
from huaweicloudsdkies.v1.model.show_edge_site_response import ShowEdgeSiteResponse
from huaweicloudsdkies.v1.model.show_rack_request import ShowRackRequest
from huaweicloudsdkies.v1.model.show_rack_response import ShowRackResponse
from huaweicloudsdkies.v1.model.show_storage_pool_request import ShowStoragePoolRequest
from huaweicloudsdkies.v1.model.show_storage_pool_response import ShowStoragePoolResponse
from huaweicloudsdkies.v1.model.site_status import SiteStatus
from huaweicloudsdkies.v1.model.storage_pool import StoragePool
from huaweicloudsdkies.v1.model.storage_pool_status import StoragePoolStatus
from huaweicloudsdkies.v1.model.storage_type import StorageType
from huaweicloudsdkies.v1.model.storage_unit import StorageUnit
from huaweicloudsdkies.v1.model.update_condition import UpdateCondition
from huaweicloudsdkies.v1.model.update_edge_site import UpdateEdgeSite
from huaweicloudsdkies.v1.model.update_edge_site_request import UpdateEdgeSiteRequest
from huaweicloudsdkies.v1.model.update_edge_site_request_body import UpdateEdgeSiteRequestBody
from huaweicloudsdkies.v1.model.update_edge_site_response import UpdateEdgeSiteResponse
from huaweicloudsdkies.v1.model.update_location import UpdateLocation

