# coding: utf-8

from __future__ import absolute_import

# import models into model package
from huaweicloudsdkantiddos.v2.model.alert_config_resp_warn_config import AlertConfigRespWarnConfig
from huaweicloudsdkantiddos.v2.model.clean_limit_dict import CleanLimitDict
from huaweicloudsdkantiddos.v2.model.d_dos_status import DDosStatus
from huaweicloudsdkantiddos.v2.model.extend_d_do_s_set import ExtendDDoSSet
from huaweicloudsdkantiddos.v2.model.list_d_dos_status_request import ListDDosStatusRequest
from huaweicloudsdkantiddos.v2.model.list_d_dos_status_response import ListDDosStatusResponse
from huaweicloudsdkantiddos.v2.model.list_new_configs_request import ListNewConfigsRequest
from huaweicloudsdkantiddos.v2.model.list_new_configs_response import ListNewConfigsResponse
from huaweicloudsdkantiddos.v2.model.show_alert_config_request import ShowAlertConfigRequest
from huaweicloudsdkantiddos.v2.model.show_alert_config_response import ShowAlertConfigResponse
from huaweicloudsdkantiddos.v2.model.show_new_task_status_request import ShowNewTaskStatusRequest
from huaweicloudsdkantiddos.v2.model.show_new_task_status_response import ShowNewTaskStatusResponse
from huaweicloudsdkantiddos.v2.model.trigger_bps_dict import TriggerBpsDict
from huaweicloudsdkantiddos.v2.model.trigger_qps_dict import TriggerQpsDict
from huaweicloudsdkantiddos.v2.model.update_alert_config_request import UpdateAlertConfigRequest
from huaweicloudsdkantiddos.v2.model.update_alert_config_request_body import UpdateAlertConfigRequestBody
from huaweicloudsdkantiddos.v2.model.update_alert_config_response import UpdateAlertConfigResponse
from huaweicloudsdkantiddos.v2.model.warn_config import WarnConfig
