# coding: utf-8

from __future__ import absolute_import

# import models into model package
from huaweicloudsdkoms.v2.model.bandwidth_policy_dto import BandwidthPolicyDto
from huaweicloudsdkoms.v2.model.create_sync_events_request import CreateSyncEventsRequest
from huaweicloudsdkoms.v2.model.create_sync_events_response import CreateSyncEventsResponse
from huaweicloudsdkoms.v2.model.create_task_req import CreateTaskReq
from huaweicloudsdkoms.v2.model.create_task_request import CreateTaskRequest
from huaweicloudsdkoms.v2.model.create_task_response import CreateTaskResponse
from huaweicloudsdkoms.v2.model.delete_task_request import DeleteTaskRequest
from huaweicloudsdkoms.v2.model.delete_task_response import DeleteTaskResponse
from huaweicloudsdkoms.v2.model.dst_node_req import DstNodeReq
from huaweicloudsdkoms.v2.model.dst_node_resp import DstNodeResp
from huaweicloudsdkoms.v2.model.error_reason_resp import ErrorReasonResp
from huaweicloudsdkoms.v2.model.failed_object_record_dto import FailedObjectRecordDto
from huaweicloudsdkoms.v2.model.link import Link
from huaweicloudsdkoms.v2.model.list_api_versions_request import ListApiVersionsRequest
from huaweicloudsdkoms.v2.model.list_api_versions_response import ListApiVersionsResponse
from huaweicloudsdkoms.v2.model.list_file import ListFile
from huaweicloudsdkoms.v2.model.list_tasks_request import ListTasksRequest
from huaweicloudsdkoms.v2.model.list_tasks_response import ListTasksResponse
from huaweicloudsdkoms.v2.model.show_api_info_request import ShowApiInfoRequest
from huaweicloudsdkoms.v2.model.show_api_info_response import ShowApiInfoResponse
from huaweicloudsdkoms.v2.model.show_task_request import ShowTaskRequest
from huaweicloudsdkoms.v2.model.show_task_response import ShowTaskResponse
from huaweicloudsdkoms.v2.model.smn_config import SmnConfig
from huaweicloudsdkoms.v2.model.smn_info import SmnInfo
from huaweicloudsdkoms.v2.model.source_cdn_req import SourceCdnReq
from huaweicloudsdkoms.v2.model.source_cdn_resp import SourceCdnResp
from huaweicloudsdkoms.v2.model.src_node_req import SrcNodeReq
from huaweicloudsdkoms.v2.model.src_node_resp import SrcNodeResp
from huaweicloudsdkoms.v2.model.start_task_req import StartTaskReq
from huaweicloudsdkoms.v2.model.start_task_request import StartTaskRequest
from huaweicloudsdkoms.v2.model.start_task_response import StartTaskResponse
from huaweicloudsdkoms.v2.model.stop_task_request import StopTaskRequest
from huaweicloudsdkoms.v2.model.stop_task_response import StopTaskResponse
from huaweicloudsdkoms.v2.model.sync_object_req import SyncObjectReq
from huaweicloudsdkoms.v2.model.task_resp import TaskResp
from huaweicloudsdkoms.v2.model.update_bandwidth_policy_req import UpdateBandwidthPolicyReq
from huaweicloudsdkoms.v2.model.update_bandwidth_policy_request import UpdateBandwidthPolicyRequest
from huaweicloudsdkoms.v2.model.update_bandwidth_policy_response import UpdateBandwidthPolicyResponse
from huaweicloudsdkoms.v2.model.version import Version
