# coding: utf-8

from __future__ import absolute_import

# import models into model package
from huaweicloudsdkmoderation.v2.model.check_result_items_body import CheckResultItemsBody
from huaweicloudsdkmoderation.v2.model.check_result_result_body import CheckResultResultBody
from huaweicloudsdkmoderation.v2.model.check_task_jobs_items_body import CheckTaskJobsItemsBody
from huaweicloudsdkmoderation.v2.model.image_batch_moderation_req import ImageBatchModerationReq
from huaweicloudsdkmoderation.v2.model.image_batch_moderation_result_body import ImageBatchModerationResultBody
from huaweicloudsdkmoderation.v2.model.image_detection_req import ImageDetectionReq
from huaweicloudsdkmoderation.v2.model.image_detection_result_ad_detail import ImageDetectionResultAdDetail
from huaweicloudsdkmoderation.v2.model.image_detection_result_body import ImageDetectionResultBody
from huaweicloudsdkmoderation.v2.model.image_detection_result_detail import ImageDetectionResultDetail
from huaweicloudsdkmoderation.v2.model.image_detection_result_detail_face_detail import ImageDetectionResultDetailFaceDetail
from huaweicloudsdkmoderation.v2.model.image_detection_result_detail_politics import ImageDetectionResultDetailPolitics
from huaweicloudsdkmoderation.v2.model.image_detection_result_simple_detail import ImageDetectionResultSimpleDetail
from huaweicloudsdkmoderation.v2.model.porn_moderation_result_detail import PornModerationResultDetail
from huaweicloudsdkmoderation.v2.model.run_check_result_request import RunCheckResultRequest
from huaweicloudsdkmoderation.v2.model.run_check_result_response import RunCheckResultResponse
from huaweicloudsdkmoderation.v2.model.run_check_task_jobs_request import RunCheckTaskJobsRequest
from huaweicloudsdkmoderation.v2.model.run_check_task_jobs_response import RunCheckTaskJobsResponse
from huaweicloudsdkmoderation.v2.model.run_image_batch_moderation_request import RunImageBatchModerationRequest
from huaweicloudsdkmoderation.v2.model.run_image_batch_moderation_response import RunImageBatchModerationResponse
from huaweicloudsdkmoderation.v2.model.run_image_moderation_request import RunImageModerationRequest
from huaweicloudsdkmoderation.v2.model.run_image_moderation_response import RunImageModerationResponse
from huaweicloudsdkmoderation.v2.model.run_moderation_audio_request import RunModerationAudioRequest
from huaweicloudsdkmoderation.v2.model.run_moderation_audio_request_body import RunModerationAudioRequestBody
from huaweicloudsdkmoderation.v2.model.run_moderation_audio_request_body_config import RunModerationAudioRequestBodyConfig
from huaweicloudsdkmoderation.v2.model.run_moderation_audio_response import RunModerationAudioResponse
from huaweicloudsdkmoderation.v2.model.run_moderation_audio_response_body_result import RunModerationAudioResponseBodyResult
from huaweicloudsdkmoderation.v2.model.run_moderation_audio_response_body_result_detail import RunModerationAudioResponseBodyResultDetail
from huaweicloudsdkmoderation.v2.model.run_moderation_audio_response_body_result_detail_audio import RunModerationAudioResponseBodyResultDetailAudio
from huaweicloudsdkmoderation.v2.model.run_task_sumbit_request import RunTaskSumbitRequest
from huaweicloudsdkmoderation.v2.model.run_task_sumbit_response import RunTaskSumbitResponse
from huaweicloudsdkmoderation.v2.model.run_text_moderation_request import RunTextModerationRequest
from huaweicloudsdkmoderation.v2.model.run_text_moderation_response import RunTextModerationResponse
from huaweicloudsdkmoderation.v2.model.task_sumbit_req import TaskSumbitReq
from huaweicloudsdkmoderation.v2.model.task_sumbit_response_result import TaskSumbitResponseResult
from huaweicloudsdkmoderation.v2.model.text_detection_items_req import TextDetectionItemsReq
from huaweicloudsdkmoderation.v2.model.text_detection_req import TextDetectionReq
from huaweicloudsdkmoderation.v2.model.text_detection_response_result import TextDetectionResponseResult
