# coding: utf-8

from __future__ import absolute_import

# import ImageClient
from huaweicloudsdkimage.v1.image_client import ImageClient
from huaweicloudsdkimage.v1.image_async_client import ImageAsyncClient
# import models into sdk package
from huaweicloudsdkimage.v1.model.celebrity_recognition_req import CelebrityRecognitionReq
from huaweicloudsdkimage.v1.model.celebrity_recognition_result_body import CelebrityRecognitionResultBody
from huaweicloudsdkimage.v1.model.image_tagging_body import ImageTaggingBody
from huaweicloudsdkimage.v1.model.image_tagging_i18n_tag import ImageTaggingI18nTag
from huaweicloudsdkimage.v1.model.image_tagging_item_body import ImageTaggingItemBody
from huaweicloudsdkimage.v1.model.image_tagging_req import ImageTaggingReq
from huaweicloudsdkimage.v1.model.run_celebrity_recognition_request import RunCelebrityRecognitionRequest
from huaweicloudsdkimage.v1.model.run_celebrity_recognition_response import RunCelebrityRecognitionResponse
from huaweicloudsdkimage.v1.model.run_image_tagging_request import RunImageTaggingRequest
from huaweicloudsdkimage.v1.model.run_image_tagging_response import RunImageTaggingResponse

