[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "huaweicloudsdkall"
version = "3.1.216"
description = "HuaweiCloud SDK Python All"
readme = "README_PYPI.md"
authors = [
    { name = "HuaweiCloud SDK", email = "hwcloudsdk@huawei.com" }
]
license = "Apache-2.0"
requires-python = ">=3.6"
keywords = ["huaweicloud", "sdk", "all"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development"
]
dependencies = [
    "huaweicloudsdkaad==3.1.216",
    "huaweicloudsdkagentarts==3.1.216",
    "huaweicloudsdkagentidentity==3.1.216",
    "huaweicloudsdkaidatalake==3.1.216",
    "huaweicloudsdkantiddos==3.1.216",
    "huaweicloudsdkaom==3.1.216",
    "huaweicloudsdkaos==3.1.216",
    "huaweicloudsdkapig==3.1.216",
    "huaweicloudsdkapm==3.1.216",
    "huaweicloudsdkas==3.1.216",
    "huaweicloudsdkasm==3.1.216",
    "huaweicloudsdkastrozero==3.1.216",
    "huaweicloudsdkbcc==3.1.216",
    "huaweicloudsdkbcs==3.1.216",
    "huaweicloudsdkbms==3.1.216",
    "huaweicloudsdkbss==3.1.216",
    "huaweicloudsdkbssintl==3.1.216",
    "huaweicloudsdkcae==3.1.216",
    "huaweicloudsdkcampusgo==3.1.216",
    "huaweicloudsdkcbh==3.1.216",
    "huaweicloudsdkcbr==3.1.216",
    "huaweicloudsdkcbs==3.1.216",
    "huaweicloudsdkcc==3.1.216",
    "huaweicloudsdkcce==3.1.216",
    "huaweicloudsdkccm==3.1.216",
    "huaweicloudsdkcdm==3.1.216",
    "huaweicloudsdkcdn==3.1.216",
    "huaweicloudsdkces==3.1.216",
    "huaweicloudsdkcfw==3.1.216",
    "huaweicloudsdkclassroom==3.1.216",
    "huaweicloudsdkclouddc==3.1.216",
    "huaweicloudsdkcloudide==3.1.216",
    "huaweicloudsdkcloudpond==3.1.216",
    "huaweicloudsdkcloudrtc==3.1.216",
    "huaweicloudsdkcloudtable==3.1.216",
    "huaweicloudsdkcloudtest==3.1.216",
    "huaweicloudsdkcoc==3.1.216",
    "huaweicloudsdkcodeartsartifact==3.1.216",
    "huaweicloudsdkcodeartsbuild==3.1.216",
    "huaweicloudsdkcodeartscheck==3.1.216",
    "huaweicloudsdkcodeartsdeploy==3.1.216",
    "huaweicloudsdkcodeartsgovernance==3.1.216",
    "huaweicloudsdkcodeartside==3.1.216",
    "huaweicloudsdkcodeartsinspector==3.1.216",
    "huaweicloudsdkcodeartspipeline==3.1.216",
    "huaweicloudsdkcodeartsrepo==3.1.216",
    "huaweicloudsdkcodecraft==3.1.216",
    "huaweicloudsdkconfig==3.1.216",
    "huaweicloudsdkcpcs==3.1.216",
    "huaweicloudsdkcph==3.1.216",
    "huaweicloudsdkcpts==3.1.216",
    "huaweicloudsdkcse==3.1.216",
    "huaweicloudsdkcsms==3.1.216",
    "huaweicloudsdkcss==3.1.216",
    "huaweicloudsdkcts==3.1.216",
    "huaweicloudsdkdas==3.1.216",
    "huaweicloudsdkdataartsfabric==3.1.216",
    "huaweicloudsdkdataartsfabricep==3.1.216",
    "huaweicloudsdkdataartsstudio==3.1.216",
    "huaweicloudsdkdbss==3.1.216",
    "huaweicloudsdkdc==3.1.216",
    "huaweicloudsdkdcc==3.1.216",
    "huaweicloudsdkdcos==3.1.216",
    "huaweicloudsdkdcs==3.1.216",
    "huaweicloudsdkddm==3.1.216",
    "huaweicloudsdkdds==3.1.216",
    "huaweicloudsdkdeh==3.1.216",
    "huaweicloudsdkdevstar==3.1.216",
    "huaweicloudsdkdgc==3.1.216",
    "huaweicloudsdkdis==3.1.216",
    "huaweicloudsdkdlf==3.1.216",
    "huaweicloudsdkdli==3.1.216",
    "huaweicloudsdkdns==3.1.216",
    "huaweicloudsdkdris==3.1.216",
    "huaweicloudsdkdrs==3.1.216",
    "huaweicloudsdkdsc==3.1.216",
    "huaweicloudsdkdwr==3.1.216",
    "huaweicloudsdkdws==3.1.216",
    "huaweicloudsdkec==3.1.216",
    "huaweicloudsdkecs==3.1.216",
    "huaweicloudsdkedgesec==3.1.216",
    "huaweicloudsdkeg==3.1.216",
    "huaweicloudsdkeihealth==3.1.216",
    "huaweicloudsdkeip==3.1.216",
    "huaweicloudsdkelb==3.1.216",
    "huaweicloudsdkeps==3.1.216",
    "huaweicloudsdker==3.1.216",
    "huaweicloudsdkesw==3.1.216",
    "huaweicloudsdkevs==3.1.216",
    "huaweicloudsdkfrs==3.1.216",
    "huaweicloudsdkfunctiongraph==3.1.216",
    "huaweicloudsdkga==3.1.216",
    "huaweicloudsdkgaussdb==3.1.216",
    "huaweicloudsdkgaussdbfornosql==3.1.216",
    "huaweicloudsdkgaussdbforopengauss==3.1.216",
    "huaweicloudsdkgeip==3.1.216",
    "huaweicloudsdkges==3.1.216",
    "huaweicloudsdkgsl==3.1.216",
    "huaweicloudsdkhilens==3.1.216",
    "huaweicloudsdkhss==3.1.216",
    "huaweicloudsdkiam==3.1.216",
    "huaweicloudsdkiamaccessanalyzer==3.1.216",
    "huaweicloudsdkidentitycenter==3.1.216",
    "huaweicloudsdkidentitycenteroidc==3.1.216",
    "huaweicloudsdkidentitycenterportalapi==3.1.216",
    "huaweicloudsdkidentitycenterscim==3.1.216",
    "huaweicloudsdkidentitycenterstore==3.1.216",
    "huaweicloudsdkidme==3.1.216",
    "huaweicloudsdkidmeclassicapi==3.1.216",
    "huaweicloudsdkiec==3.1.216",
    "huaweicloudsdkief==3.1.216",
    "huaweicloudsdkimage==3.1.216",
    "huaweicloudsdkimagesearch==3.1.216",
    "huaweicloudsdkims==3.1.216",
    "huaweicloudsdkiotanalytics==3.1.216",
    "huaweicloudsdkiotda==3.1.216",
    "huaweicloudsdkiotdm==3.1.216",
    "huaweicloudsdkiotedge==3.1.216",
    "huaweicloudsdkivs==3.1.216",
    "huaweicloudsdkkafka==3.1.216",
    "huaweicloudsdkkms==3.1.216",
    "huaweicloudsdkkoomessage==3.1.216",
    "huaweicloudsdkkps==3.1.216",
    "huaweicloudsdkkvs==3.1.216",
    "huaweicloudsdklakeformation==3.1.216",
    "huaweicloudsdklive==3.1.216",
    "huaweicloudsdklts==3.1.216",
    "huaweicloudsdkmapds==3.1.216",
    "huaweicloudsdkmas==3.1.216",
    "huaweicloudsdkmastudio==3.1.216",
    "huaweicloudsdkmeeting==3.1.216",
    "huaweicloudsdkmetastudio==3.1.216",
    "huaweicloudsdkmodelarts==3.1.216",
    "huaweicloudsdkmoderation==3.1.216",
    "huaweicloudsdkmpc==3.1.216",
    "huaweicloudsdkmrs==3.1.216",
    "huaweicloudsdkmsgsms==3.1.216",
    "huaweicloudsdkmssi==3.1.216",
    "huaweicloudsdknat==3.1.216",
    "huaweicloudsdknlp==3.1.216",
    "huaweicloudsdkobs==3.1.216",
    "huaweicloudsdkocr==3.1.216",
    "huaweicloudsdkoctopus==3.1.216",
    "huaweicloudsdkoms==3.1.216",
    "huaweicloudsdkoptverse==3.1.216",
    "huaweicloudsdkorganizations==3.1.216",
    "huaweicloudsdkorgid==3.1.216",
    "huaweicloudsdkoroas==3.1.216",
    "huaweicloudsdkosm==3.1.216",
    "huaweicloudsdkpangulargemodels==3.1.216",
    "huaweicloudsdkprojectman==3.1.216",
    "huaweicloudsdkrabbitmq==3.1.216",
    "huaweicloudsdkram==3.1.216",
    "huaweicloudsdkrc==3.1.216",
    "huaweicloudsdkrds==3.1.216",
    "huaweicloudsdkres==3.1.216",
    "huaweicloudsdkrfs==3.1.216",
    "huaweicloudsdkrgc==3.1.216",
    "huaweicloudsdkrms==3.1.216",
    "huaweicloudsdkrocketmq==3.1.216",
    "huaweicloudsdkroma==3.1.216",
    "huaweicloudsdksa==3.1.216",
    "huaweicloudsdkscm==3.1.216",
    "huaweicloudsdksdrs==3.1.216",
    "huaweicloudsdksecmaster==3.1.216",
    "huaweicloudsdkservicestage==3.1.216",
    "huaweicloudsdksfsturbo==3.1.216",
    "huaweicloudsdksis==3.1.216",
    "huaweicloudsdksmn==3.1.216",
    "huaweicloudsdksmnglobal==3.1.216",
    "huaweicloudsdksms==3.1.216",
    "huaweicloudsdksmsapi==3.1.216",
    "huaweicloudsdksts==3.1.216",
    "huaweicloudsdkswr==3.1.216",
    "huaweicloudsdktics==3.1.216",
    "huaweicloudsdktms==3.1.216",
    "huaweicloudsdkucs==3.1.216",
    "huaweicloudsdkugo==3.1.216",
    "huaweicloudsdkvas==3.1.216",
    "huaweicloudsdkvcm==3.1.216",
    "huaweicloudsdkversatile==3.1.216",
    "huaweicloudsdkvod==3.1.216",
    "huaweicloudsdkvpc==3.1.216",
    "huaweicloudsdkvpcep==3.1.216",
    "huaweicloudsdkvpn==3.1.216",
    "huaweicloudsdkwaf==3.1.216",
    "huaweicloudsdkworkspace==3.1.216",
    "huaweicloudsdkworkspaceapp==3.1.216"
]

[project.urls]
Homepage = "https://github.com/huaweicloud/huaweicloud-sdk-python-v3"