# coding: utf-8

from __future__ import absolute_import

from huaweicloudsdkrc.v1.rc_client import RcClient
from huaweicloudsdkrc.v1.rc_async_client import RcAsyncClient

from huaweicloudsdkrc.v1.model.add_resources_request_body import AddResourcesRequestBody
from huaweicloudsdkrc.v1.model.add_resources_to_group_request import AddResourcesToGroupRequest
from huaweicloudsdkrc.v1.model.add_resources_to_group_response import AddResourcesToGroupResponse
from huaweicloudsdkrc.v1.model.base_resource_entity import BaseResourceEntity
from huaweicloudsdkrc.v1.model.collect_all_resources_summary_request import CollectAllResourcesSummaryRequest
from huaweicloudsdkrc.v1.model.collect_all_resources_summary_response import CollectAllResourcesSummaryResponse
from huaweicloudsdkrc.v1.model.count_all_resources_request import CountAllResourcesRequest
from huaweicloudsdkrc.v1.model.count_all_resources_response import CountAllResourcesResponse
from huaweicloudsdkrc.v1.model.create_groups_response import CreateGroupsResponse
from huaweicloudsdkrc.v1.model.create_resource_group_request import CreateResourceGroupRequest
from huaweicloudsdkrc.v1.model.create_resource_group_response import CreateResourceGroupResponse
from huaweicloudsdkrc.v1.model.delete_resource_group_request import DeleteResourceGroupRequest
from huaweicloudsdkrc.v1.model.delete_resource_group_response import DeleteResourceGroupResponse
from huaweicloudsdkrc.v1.model.generic_resource_group_request_body import GenericResourceGroupRequestBody
from huaweicloudsdkrc.v1.model.list_all_providers_request import ListAllProvidersRequest
from huaweicloudsdkrc.v1.model.list_all_providers_response import ListAllProvidersResponse
from huaweicloudsdkrc.v1.model.list_all_resources_request import ListAllResourcesRequest
from huaweicloudsdkrc.v1.model.list_all_resources_response import ListAllResourcesResponse
from huaweicloudsdkrc.v1.model.list_all_tags_request import ListAllTagsRequest
from huaweicloudsdkrc.v1.model.list_all_tags_response import ListAllTagsResponse
from huaweicloudsdkrc.v1.model.list_resource_groups_request import ListResourceGroupsRequest
from huaweicloudsdkrc.v1.model.list_resource_groups_response import ListResourceGroupsResponse
from huaweicloudsdkrc.v1.model.list_resources_request import ListResourcesRequest
from huaweicloudsdkrc.v1.model.list_resources_response import ListResourcesResponse
from huaweicloudsdkrc.v1.model.page_info import PageInfo
from huaweicloudsdkrc.v1.model.remove_resource_from_group_request import RemoveResourceFromGroupRequest
from huaweicloudsdkrc.v1.model.remove_resource_from_group_response import RemoveResourceFromGroupResponse
from huaweicloudsdkrc.v1.model.resource_entity import ResourceEntity
from huaweicloudsdkrc.v1.model.resource_provider_response import ResourceProviderResponse
from huaweicloudsdkrc.v1.model.resource_relation import ResourceRelation
from huaweicloudsdkrc.v1.model.resource_summary_response_item import ResourceSummaryResponseItem
from huaweicloudsdkrc.v1.model.resource_summary_response_item_regions import ResourceSummaryResponseItemRegions
from huaweicloudsdkrc.v1.model.resource_summary_response_item_types import ResourceSummaryResponseItemTypes
from huaweicloudsdkrc.v1.model.resource_type_response import ResourceTypeResponse
from huaweicloudsdkrc.v1.model.show_resource_by_id_request import ShowResourceByIdRequest
from huaweicloudsdkrc.v1.model.show_resource_by_id_response import ShowResourceByIdResponse
from huaweicloudsdkrc.v1.model.show_resource_detail_request import ShowResourceDetailRequest
from huaweicloudsdkrc.v1.model.show_resource_detail_response import ShowResourceDetailResponse
from huaweicloudsdkrc.v1.model.show_resource_group_request import ShowResourceGroupRequest
from huaweicloudsdkrc.v1.model.show_resource_group_response import ShowResourceGroupResponse
from huaweicloudsdkrc.v1.model.show_resource_relations_request import ShowResourceRelationsRequest
from huaweicloudsdkrc.v1.model.show_resource_relations_response import ShowResourceRelationsResponse
from huaweicloudsdkrc.v1.model.tag_detail import TagDetail
from huaweicloudsdkrc.v1.model.update_resource_group_request import UpdateResourceGroupRequest
from huaweicloudsdkrc.v1.model.update_resource_group_request_body import UpdateResourceGroupRequestBody
from huaweicloudsdkrc.v1.model.update_resource_group_response import UpdateResourceGroupResponse

