# coding: utf-8

from __future__ import absolute_import

# import models into model package
from huaweicloudsdkcloudide.v2.model.attributes import Attributes
from huaweicloudsdkcloudide.v2.model.check_name_request import CheckNameRequest
from huaweicloudsdkcloudide.v2.model.check_name_response import CheckNameResponse
from huaweicloudsdkcloudide.v2.model.create_instance_by3rd_request import CreateInstanceBy3rdRequest
from huaweicloudsdkcloudide.v2.model.create_instance_by3rd_response import CreateInstanceBy3rdResponse
from huaweicloudsdkcloudide.v2.model.create_instance_request import CreateInstanceRequest
from huaweicloudsdkcloudide.v2.model.create_instance_response import CreateInstanceResponse
from huaweicloudsdkcloudide.v2.model.delete_instance_request import DeleteInstanceRequest
from huaweicloudsdkcloudide.v2.model.delete_instance_response import DeleteInstanceResponse
from huaweicloudsdkcloudide.v2.model.instance_edge_param import InstanceEdgeParam
from huaweicloudsdkcloudide.v2.model.instance_param import InstanceParam
from huaweicloudsdkcloudide.v2.model.instance_update_param import InstanceUpdateParam
from huaweicloudsdkcloudide.v2.model.instances_vo import InstancesVO
from huaweicloudsdkcloudide.v2.model.list_instances_request import ListInstancesRequest
from huaweicloudsdkcloudide.v2.model.list_instances_response import ListInstancesResponse
from huaweicloudsdkcloudide.v2.model.list_org_instances_request import ListOrgInstancesRequest
from huaweicloudsdkcloudide.v2.model.list_org_instances_response import ListOrgInstancesResponse
from huaweicloudsdkcloudide.v2.model.list_project_templates_request import ListProjectTemplatesRequest
from huaweicloudsdkcloudide.v2.model.list_project_templates_response import ListProjectTemplatesResponse
from huaweicloudsdkcloudide.v2.model.list_stacks_by_tag_request import ListStacksByTagRequest
from huaweicloudsdkcloudide.v2.model.list_stacks_by_tag_response import ListStacksByTagResponse
from huaweicloudsdkcloudide.v2.model.page_instances_vo import PageInstancesVO
from huaweicloudsdkcloudide.v2.model.plugin import Plugin
from huaweicloudsdkcloudide.v2.model.project_templates import ProjectTemplates
from huaweicloudsdkcloudide.v2.model.recipe import Recipe
from huaweicloudsdkcloudide.v2.model.resource_price import ResourcePrice
from huaweicloudsdkcloudide.v2.model.role import Role
from huaweicloudsdkcloudide.v2.model.role_action import RoleAction
from huaweicloudsdkcloudide.v2.model.show_instance_request import ShowInstanceRequest
from huaweicloudsdkcloudide.v2.model.show_instance_response import ShowInstanceResponse
from huaweicloudsdkcloudide.v2.model.show_price_request import ShowPriceRequest
from huaweicloudsdkcloudide.v2.model.show_price_response import ShowPriceResponse
from huaweicloudsdkcloudide.v2.model.source_storage import SourceStorage
from huaweicloudsdkcloudide.v2.model.stacks import Stacks
from huaweicloudsdkcloudide.v2.model.stacks_attribute import StacksAttribute
from huaweicloudsdkcloudide.v2.model.stacks_config import StacksConfig
from huaweicloudsdkcloudide.v2.model.stacks_tag import StacksTag
from huaweicloudsdkcloudide.v2.model.start_instance_request import StartInstanceRequest
from huaweicloudsdkcloudide.v2.model.start_instance_response import StartInstanceResponse
from huaweicloudsdkcloudide.v2.model.stop_instance_request import StopInstanceRequest
from huaweicloudsdkcloudide.v2.model.stop_instance_response import StopInstanceResponse
from huaweicloudsdkcloudide.v2.model.update_instance_request import UpdateInstanceRequest
from huaweicloudsdkcloudide.v2.model.update_instance_response import UpdateInstanceResponse
