# coding: utf-8

from __future__ import absolute_import

# import models into model package
from huaweicloudsdkcodecraft.v5.model.create_competition_score_request import CreateCompetitionScoreRequest
from huaweicloudsdkcodecraft.v5.model.create_competition_score_response import CreateCompetitionScoreResponse
from huaweicloudsdkcodecraft.v5.model.create_scores_request_model import CreateScoresRequestModel
from huaweicloudsdkcodecraft.v5.model.list_competition_works_request import ListCompetitionWorksRequest
from huaweicloudsdkcodecraft.v5.model.list_competition_works_response import ListCompetitionWorksResponse
from huaweicloudsdkcodecraft.v5.model.list_works_response_model import ListWorksResponseModel
from huaweicloudsdkcodecraft.v5.model.register_competition_info_request import RegisterCompetitionInfoRequest
from huaweicloudsdkcodecraft.v5.model.register_competition_info_response import RegisterCompetitionInfoResponse
from huaweicloudsdkcodecraft.v5.model.register_info_request_model import RegisterInfoRequestModel
from huaweicloudsdkcodecraft.v5.model.update_competition_score_request import UpdateCompetitionScoreRequest
from huaweicloudsdkcodecraft.v5.model.update_competition_score_response import UpdateCompetitionScoreResponse
from huaweicloudsdkcodecraft.v5.model.update_score_request_model import UpdateScoreRequestModel
