# coding: utf-8

from __future__ import absolute_import

from huaweicloudsdkdeh.v1.deh_client import DeHClient
from huaweicloudsdkdeh.v1.deh_async_client import DeHAsyncClient

from huaweicloudsdkdeh.v1.model.batch_create_dedicated_host_tags_request import BatchCreateDedicatedHostTagsRequest
from huaweicloudsdkdeh.v1.model.batch_create_dedicated_host_tags_response import BatchCreateDedicatedHostTagsResponse
from huaweicloudsdkdeh.v1.model.batch_delete_dedicated_host_tags_request import BatchDeleteDedicatedHostTagsRequest
from huaweicloudsdkdeh.v1.model.batch_delete_dedicated_host_tags_response import BatchDeleteDedicatedHostTagsResponse
from huaweicloudsdkdeh.v1.model.create_dedicated_host_request import CreateDedicatedHostRequest
from huaweicloudsdkdeh.v1.model.create_dedicated_host_response import CreateDedicatedHostResponse
from huaweicloudsdkdeh.v1.model.delete_dedicated_host_request import DeleteDedicatedHostRequest
from huaweicloudsdkdeh.v1.model.delete_dedicated_host_response import DeleteDedicatedHostResponse
from huaweicloudsdkdeh.v1.model.list_dedicated_host_types_request import ListDedicatedHostTypesRequest
from huaweicloudsdkdeh.v1.model.list_dedicated_host_types_response import ListDedicatedHostTypesResponse
from huaweicloudsdkdeh.v1.model.list_dedicated_hosts_by_tags_request import ListDedicatedHostsByTagsRequest
from huaweicloudsdkdeh.v1.model.list_dedicated_hosts_by_tags_response import ListDedicatedHostsByTagsResponse
from huaweicloudsdkdeh.v1.model.list_dedicated_hosts_request import ListDedicatedHostsRequest
from huaweicloudsdkdeh.v1.model.list_dedicated_hosts_response import ListDedicatedHostsResponse
from huaweicloudsdkdeh.v1.model.list_servers_dedicated_host_request import ListServersDedicatedHostRequest
from huaweicloudsdkdeh.v1.model.list_servers_dedicated_host_response import ListServersDedicatedHostResponse
from huaweicloudsdkdeh.v1.model.match import Match
from huaweicloudsdkdeh.v1.model.req_allocate_deh import ReqAllocateDeh
from huaweicloudsdkdeh.v1.model.req_list_deh_by_tags import ReqListDehByTags
from huaweicloudsdkdeh.v1.model.req_set_or_delete_tags import ReqSetOrDeleteTags
from huaweicloudsdkdeh.v1.model.req_update_deh import ReqUpdateDeh
from huaweicloudsdkdeh.v1.model.req_update_deh_message import ReqUpdateDehMessage
from huaweicloudsdkdeh.v1.model.resource_tag import ResourceTag
from huaweicloudsdkdeh.v1.model.resp_addr import RespAddr
from huaweicloudsdkdeh.v1.model.resp_dedicated_host import RespDedicatedHost
from huaweicloudsdkdeh.v1.model.resp_deh import RespDeh
from huaweicloudsdkdeh.v1.model.resp_flavor import RespFlavor
from huaweicloudsdkdeh.v1.model.resp_host_property import RespHostProperty
from huaweicloudsdkdeh.v1.model.resp_host_type import RespHostType
from huaweicloudsdkdeh.v1.model.resp_image import RespImage
from huaweicloudsdkdeh.v1.model.resp_instance_capacity import RespInstanceCapacity
from huaweicloudsdkdeh.v1.model.resp_metadata import RespMetadata
from huaweicloudsdkdeh.v1.model.resp_quota_set import RespQuotaSet
from huaweicloudsdkdeh.v1.model.resp_server import RespServer
from huaweicloudsdkdeh.v1.model.show_dedicated_host_request import ShowDedicatedHostRequest
from huaweicloudsdkdeh.v1.model.show_dedicated_host_response import ShowDedicatedHostResponse
from huaweicloudsdkdeh.v1.model.show_dedicated_host_tags_request import ShowDedicatedHostTagsRequest
from huaweicloudsdkdeh.v1.model.show_dedicated_host_tags_response import ShowDedicatedHostTagsResponse
from huaweicloudsdkdeh.v1.model.show_quota_sets_request import ShowQuotaSetsRequest
from huaweicloudsdkdeh.v1.model.show_quota_sets_response import ShowQuotaSetsResponse
from huaweicloudsdkdeh.v1.model.tag import Tag
from huaweicloudsdkdeh.v1.model.update_dedicated_host_request import UpdateDedicatedHostRequest
from huaweicloudsdkdeh.v1.model.update_dedicated_host_response import UpdateDedicatedHostResponse

