# coding: utf-8

from __future__ import absolute_import

from huaweicloudsdkcc.v2.cc_client import CcClient
from huaweicloudsdkcc.v2.cc_async_client import CcAsyncClient

from huaweicloudsdkcc.v2.model.agg_tag import AggTag
from huaweicloudsdkcc.v2.model.batch_create_delete_tags_request import BatchCreateDeleteTagsRequest
from huaweicloudsdkcc.v2.model.batch_create_delete_tags_response import BatchCreateDeleteTagsResponse
from huaweicloudsdkcc.v2.model.batch_create_gcb_resource_tags_request import BatchCreateGcbResourceTagsRequest
from huaweicloudsdkcc.v2.model.batch_create_gcb_resource_tags_response import BatchCreateGcbResourceTagsResponse
from huaweicloudsdkcc.v2.model.batch_delete_gcb_resource_tags_request import BatchDeleteGcbResourceTagsRequest
from huaweicloudsdkcc.v2.model.batch_delete_gcb_resource_tags_response import BatchDeleteGcbResourceTagsResponse
from huaweicloudsdkcc.v2.model.count_gcb_resource_by_tag_request import CountGcbResourceByTagRequest
from huaweicloudsdkcc.v2.model.count_gcb_resource_by_tag_response import CountGcbResourceByTagResponse
from huaweicloudsdkcc.v2.model.create_delete_gcb_tags_request_body import CreateDeleteGcbTagsRequestBody
from huaweicloudsdkcc.v2.model.create_gcb_resource_tag_request import CreateGcbResourceTagRequest
from huaweicloudsdkcc.v2.model.create_gcb_resource_tag_response import CreateGcbResourceTagResponse
from huaweicloudsdkcc.v2.model.create_gcb_tag_request_body import CreateGcbTagRequestBody
from huaweicloudsdkcc.v2.model.create_tag_request import CreateTagRequest
from huaweicloudsdkcc.v2.model.create_tag_request_body import CreateTagRequestBody
from huaweicloudsdkcc.v2.model.create_tag_response import CreateTagResponse
from huaweicloudsdkcc.v2.model.delete_gcb_resource_tag_request import DeleteGcbResourceTagRequest
from huaweicloudsdkcc.v2.model.delete_gcb_resource_tag_response import DeleteGcbResourceTagResponse
from huaweicloudsdkcc.v2.model.delete_tag_request import DeleteTagRequest
from huaweicloudsdkcc.v2.model.delete_tag_response import DeleteTagResponse
from huaweicloudsdkcc.v2.model.filter_tag_resource import FilterTagResource
from huaweicloudsdkcc.v2.model.list_domain_tags_request import ListDomainTagsRequest
from huaweicloudsdkcc.v2.model.list_domain_tags_response import ListDomainTagsResponse
from huaweicloudsdkcc.v2.model.list_gcb_resource_by_tag_request import ListGcbResourceByTagRequest
from huaweicloudsdkcc.v2.model.list_gcb_resource_by_tag_response import ListGcbResourceByTagResponse
from huaweicloudsdkcc.v2.model.list_gcb_resource_tags_request import ListGcbResourceTagsRequest
from huaweicloudsdkcc.v2.model.list_gcb_resource_tags_response import ListGcbResourceTagsResponse
from huaweicloudsdkcc.v2.model.list_gcb_tenant_tags_request import ListGcbTenantTagsRequest
from huaweicloudsdkcc.v2.model.list_gcb_tenant_tags_response import ListGcbTenantTagsResponse
from huaweicloudsdkcc.v2.model.list_resource_by_filter_tag_request import ListResourceByFilterTagRequest
from huaweicloudsdkcc.v2.model.list_resource_by_filter_tag_request_body import ListResourceByFilterTagRequestBody
from huaweicloudsdkcc.v2.model.list_resource_by_filter_tag_response import ListResourceByFilterTagResponse
from huaweicloudsdkcc.v2.model.list_tags_request import ListTagsRequest
from huaweicloudsdkcc.v2.model.list_tags_response import ListTagsResponse
from huaweicloudsdkcc.v2.model.query_resource_by_tag_request_body import QueryResourceByTagRequestBody
from huaweicloudsdkcc.v2.model.query_tag import QueryTag
from huaweicloudsdkcc.v2.model.required_tag import RequiredTag
from huaweicloudsdkcc.v2.model.resource_tags import ResourceTags
from huaweicloudsdkcc.v2.model.tag import Tag
from huaweicloudsdkcc.v2.model.tms_match import TmsMatch
from huaweicloudsdkcc.v2.model.tms_resource import TmsResource
from huaweicloudsdkcc.v2.model.tms_tag_values import TmsTagValues

