# coding: utf-8

from __future__ import absolute_import

# import models into model package
from huaweicloudsdktms.v1.model.create_predefine_tags_request import CreatePredefineTagsRequest
from huaweicloudsdktms.v1.model.create_predefine_tags_response import CreatePredefineTagsResponse
from huaweicloudsdktms.v1.model.delete_predefine_tags_request import DeletePredefineTagsRequest
from huaweicloudsdktms.v1.model.delete_predefine_tags_response import DeletePredefineTagsResponse
from huaweicloudsdktms.v1.model.link import Link
from huaweicloudsdktms.v1.model.list_api_versions_request import ListApiVersionsRequest
from huaweicloudsdktms.v1.model.list_api_versions_response import ListApiVersionsResponse
from huaweicloudsdktms.v1.model.list_predefine_tags_request import ListPredefineTagsRequest
from huaweicloudsdktms.v1.model.list_predefine_tags_response import ListPredefineTagsResponse
from huaweicloudsdktms.v1.model.modify_prefine_tag import ModifyPrefineTag
from huaweicloudsdktms.v1.model.predefine_tag import PredefineTag
from huaweicloudsdktms.v1.model.predefine_tag_request import PredefineTagRequest
from huaweicloudsdktms.v1.model.req_create_predefine_tag import ReqCreatePredefineTag
from huaweicloudsdktms.v1.model.req_delete_predefine_tag import ReqDeletePredefineTag
from huaweicloudsdktms.v1.model.show_api_version_request import ShowApiVersionRequest
from huaweicloudsdktms.v1.model.show_api_version_response import ShowApiVersionResponse
from huaweicloudsdktms.v1.model.update_predefine_tags_request import UpdatePredefineTagsRequest
from huaweicloudsdktms.v1.model.update_predefine_tags_response import UpdatePredefineTagsResponse
from huaweicloudsdktms.v1.model.version_detail import VersionDetail
