# coding: utf-8

from __future__ import absolute_import

# import models into model package
from huaweicloudsdksmsapi.v1.model.batch_send_diff_sms_request import BatchSendDiffSmsRequest
from huaweicloudsdksmsapi.v1.model.batch_send_diff_sms_request_body import BatchSendDiffSmsRequestBody
from huaweicloudsdksmsapi.v1.model.batch_send_diff_sms_response import BatchSendDiffSmsResponse
from huaweicloudsdksmsapi.v1.model.batch_send_sms_request import BatchSendSmsRequest
from huaweicloudsdksmsapi.v1.model.batch_send_sms_request_body import BatchSendSmsRequestBody
from huaweicloudsdksmsapi.v1.model.batch_send_sms_response import BatchSendSmsResponse
from huaweicloudsdksmsapi.v1.model.sms_content import SmsContent
from huaweicloudsdksmsapi.v1.model.sms_id import SmsID
