# coding: utf-8

from __future__ import absolute_import

# import IvsClient
from huaweicloudsdkivs.v2.ivs_client import IvsClient
from huaweicloudsdkivs.v2.ivs_async_client import IvsAsyncClient
# import models into sdk package
from huaweicloudsdkivs.v2.model.detect_extention_by_id_card_image_request import DetectExtentionByIdCardImageRequest
from huaweicloudsdkivs.v2.model.detect_extention_by_id_card_image_response import DetectExtentionByIdCardImageResponse
from huaweicloudsdkivs.v2.model.detect_extention_by_name_and_id_request import DetectExtentionByNameAndIdRequest
from huaweicloudsdkivs.v2.model.detect_extention_by_name_and_id_response import DetectExtentionByNameAndIdResponse
from huaweicloudsdkivs.v2.model.detect_standard_by_id_card_image_request import DetectStandardByIdCardImageRequest
from huaweicloudsdkivs.v2.model.detect_standard_by_id_card_image_response import DetectStandardByIdCardImageResponse
from huaweicloudsdkivs.v2.model.detect_standard_by_name_and_id_request import DetectStandardByNameAndIdRequest
from huaweicloudsdkivs.v2.model.detect_standard_by_name_and_id_response import DetectStandardByNameAndIdResponse
from huaweicloudsdkivs.v2.model.extention_req_data_by_id_card_image import ExtentionReqDataByIdCardImage
from huaweicloudsdkivs.v2.model.extention_req_data_by_name_and_id import ExtentionReqDataByNameAndId
from huaweicloudsdkivs.v2.model.extention_resp_data_by_id_card_image import ExtentionRespDataByIdCardImage
from huaweicloudsdkivs.v2.model.extention_resp_data_by_name_and_id import ExtentionRespDataByNameAndId
from huaweicloudsdkivs.v2.model.idcard_result import IdcardResult
from huaweicloudsdkivs.v2.model.ivs_extention_by_id_card_image_request_body import IvsExtentionByIdCardImageRequestBody
from huaweicloudsdkivs.v2.model.ivs_extention_by_id_card_image_request_body_data import IvsExtentionByIdCardImageRequestBodyData
from huaweicloudsdkivs.v2.model.ivs_extention_by_id_card_image_response_body_result import IvsExtentionByIdCardImageResponseBodyResult
from huaweicloudsdkivs.v2.model.ivs_extention_by_name_and_id_request_body import IvsExtentionByNameAndIdRequestBody
from huaweicloudsdkivs.v2.model.ivs_extention_by_name_and_id_request_body_data import IvsExtentionByNameAndIdRequestBodyData
from huaweicloudsdkivs.v2.model.ivs_extention_by_name_and_id_response_body_result import IvsExtentionByNameAndIdResponseBodyResult
from huaweicloudsdkivs.v2.model.ivs_standard_by_id_card_image_request_body import IvsStandardByIdCardImageRequestBody
from huaweicloudsdkivs.v2.model.ivs_standard_by_id_card_image_request_body_data import IvsStandardByIdCardImageRequestBodyData
from huaweicloudsdkivs.v2.model.ivs_standard_by_id_card_image_response_body_result import IvsStandardByIdCardImageResponseBodyResult
from huaweicloudsdkivs.v2.model.ivs_standard_by_name_and_id_request_body import IvsStandardByNameAndIdRequestBody
from huaweicloudsdkivs.v2.model.ivs_standard_by_name_and_id_request_body_data import IvsStandardByNameAndIdRequestBodyData
from huaweicloudsdkivs.v2.model.ivs_standard_by_name_and_id_response_body_result import IvsStandardByNameAndIdResponseBodyResult
from huaweicloudsdkivs.v2.model.meta import Meta
from huaweicloudsdkivs.v2.model.req_data_by_id_card_image import ReqDataByIdCardImage
from huaweicloudsdkivs.v2.model.resp_data_by_id_card_image import RespDataByIdCardImage
from huaweicloudsdkivs.v2.model.standard_req_data_by_name_and_id import StandardReqDataByNameAndId
from huaweicloudsdkivs.v2.model.standard_resp_data_by_name_and_id import StandardRespDataByNameAndId

