# coding: utf-8

from __future__ import absolute_import

# import DgcClient
from huaweicloudsdkdgc.v1.dgc_client import DgcClient
from huaweicloudsdkdgc.v1.dgc_async_client import DgcAsyncClient
# import models into sdk package
from huaweicloudsdkdgc.v1.model.connection_info import ConnectionInfo
from huaweicloudsdkdgc.v1.model.connection_param import ConnectionParam
from huaweicloudsdkdgc.v1.model.create_connection_request import CreateConnectionRequest
from huaweicloudsdkdgc.v1.model.create_connection_response import CreateConnectionResponse
from huaweicloudsdkdgc.v1.model.delete_connction_request import DeleteConnctionRequest
from huaweicloudsdkdgc.v1.model.delete_connction_response import DeleteConnctionResponse
from huaweicloudsdkdgc.v1.model.export_connections_request import ExportConnectionsRequest
from huaweicloudsdkdgc.v1.model.export_connections_response import ExportConnectionsResponse
from huaweicloudsdkdgc.v1.model.import_connection_req import ImportConnectionReq
from huaweicloudsdkdgc.v1.model.import_connections_request import ImportConnectionsRequest
from huaweicloudsdkdgc.v1.model.import_connections_response import ImportConnectionsResponse
from huaweicloudsdkdgc.v1.model.list_connections_request import ListConnectionsRequest
from huaweicloudsdkdgc.v1.model.list_connections_response import ListConnectionsResponse
from huaweicloudsdkdgc.v1.model.show_connection_request import ShowConnectionRequest
from huaweicloudsdkdgc.v1.model.show_connection_response import ShowConnectionResponse
from huaweicloudsdkdgc.v1.model.update_connection_request import UpdateConnectionRequest
from huaweicloudsdkdgc.v1.model.update_connection_response import UpdateConnectionResponse

