# coding: utf-8

from __future__ import absolute_import

# import models into model package
from huaweicloudsdkimage.v2.model.celebrity_recognition_req import CelebrityRecognitionReq
from huaweicloudsdkimage.v2.model.celebrity_recognition_result_body import CelebrityRecognitionResultBody
from huaweicloudsdkimage.v2.model.image_description_req import ImageDescriptionReq
from huaweicloudsdkimage.v2.model.image_description_response_result import ImageDescriptionResponseResult
from huaweicloudsdkimage.v2.model.image_main_object_detection_instance import ImageMainObjectDetectionInstance
from huaweicloudsdkimage.v2.model.image_main_object_detection_req import ImageMainObjectDetectionReq
from huaweicloudsdkimage.v2.model.image_media_tagging_det_instance import ImageMediaTaggingDetInstance
from huaweicloudsdkimage.v2.model.image_media_tagging_det_item_body import ImageMediaTaggingDetItemBody
from huaweicloudsdkimage.v2.model.image_media_tagging_det_item_body_i18n_tag import ImageMediaTaggingDetItemBodyI18nTag
from huaweicloudsdkimage.v2.model.image_media_tagging_det_req import ImageMediaTaggingDetReq
from huaweicloudsdkimage.v2.model.image_media_tagging_det_response_result import ImageMediaTaggingDetResponseResult
from huaweicloudsdkimage.v2.model.image_media_tagging_item_body import ImageMediaTaggingItemBody
from huaweicloudsdkimage.v2.model.image_media_tagging_item_body_i18n_tag import ImageMediaTaggingItemBodyI18nTag
from huaweicloudsdkimage.v2.model.image_media_tagging_item_body_i18n_type import ImageMediaTaggingItemBodyI18nType
from huaweicloudsdkimage.v2.model.image_media_tagging_req import ImageMediaTaggingReq
from huaweicloudsdkimage.v2.model.image_media_tagging_response_result import ImageMediaTaggingResponseResult
from huaweicloudsdkimage.v2.model.image_tagging_instance import ImageTaggingInstance
from huaweicloudsdkimage.v2.model.image_tagging_item_body import ImageTaggingItemBody
from huaweicloudsdkimage.v2.model.image_tagging_item_body_i18n_tag import ImageTaggingItemBodyI18nTag
from huaweicloudsdkimage.v2.model.image_tagging_item_body_i18n_type import ImageTaggingItemBodyI18nType
from huaweicloudsdkimage.v2.model.image_tagging_req import ImageTaggingReq
from huaweicloudsdkimage.v2.model.image_tagging_response_result import ImageTaggingResponseResult
from huaweicloudsdkimage.v2.model.run_celebrity_recognition_request import RunCelebrityRecognitionRequest
from huaweicloudsdkimage.v2.model.run_celebrity_recognition_response import RunCelebrityRecognitionResponse
from huaweicloudsdkimage.v2.model.run_delete_custom_tags_request import RunDeleteCustomTagsRequest
from huaweicloudsdkimage.v2.model.run_delete_custom_tags_response import RunDeleteCustomTagsResponse
from huaweicloudsdkimage.v2.model.run_image_description_request import RunImageDescriptionRequest
from huaweicloudsdkimage.v2.model.run_image_description_response import RunImageDescriptionResponse
from huaweicloudsdkimage.v2.model.run_image_main_object_detection_request import RunImageMainObjectDetectionRequest
from huaweicloudsdkimage.v2.model.run_image_main_object_detection_response import RunImageMainObjectDetectionResponse
from huaweicloudsdkimage.v2.model.run_image_media_tagging_det_request import RunImageMediaTaggingDetRequest
from huaweicloudsdkimage.v2.model.run_image_media_tagging_det_response import RunImageMediaTaggingDetResponse
from huaweicloudsdkimage.v2.model.run_image_media_tagging_request import RunImageMediaTaggingRequest
from huaweicloudsdkimage.v2.model.run_image_media_tagging_response import RunImageMediaTaggingResponse
from huaweicloudsdkimage.v2.model.run_image_tagging_request import RunImageTaggingRequest
from huaweicloudsdkimage.v2.model.run_image_tagging_response import RunImageTaggingResponse
from huaweicloudsdkimage.v2.model.run_query_custom_tags_request import RunQueryCustomTagsRequest
from huaweicloudsdkimage.v2.model.run_query_custom_tags_response import RunQueryCustomTagsResponse
