# coding: utf-8

from __future__ import absolute_import

# import ModerationClient
from huaweicloudsdkmoderation.v3.moderation_client import ModerationClient
from huaweicloudsdkmoderation.v3.moderation_async_client import ModerationAsyncClient
# import models into sdk package
from huaweicloudsdkmoderation.v3.model.audio_create_request import AudioCreateRequest
from huaweicloudsdkmoderation.v3.model.audio_input_body import AudioInputBody
from huaweicloudsdkmoderation.v3.model.audio_moderation_result_detail import AudioModerationResultDetail
from huaweicloudsdkmoderation.v3.model.audio_moderation_result_request_params import AudioModerationResultRequestParams
from huaweicloudsdkmoderation.v3.model.audio_moderation_result_request_params_data import AudioModerationResultRequestParamsData
from huaweicloudsdkmoderation.v3.model.audio_moderation_result_result import AudioModerationResultResult
from huaweicloudsdkmoderation.v3.model.check_image_moderation_request import CheckImageModerationRequest
from huaweicloudsdkmoderation.v3.model.check_image_moderation_response import CheckImageModerationResponse
from huaweicloudsdkmoderation.v3.model.face_location_detail import FaceLocationDetail
from huaweicloudsdkmoderation.v3.model.image_detection_req import ImageDetectionReq
from huaweicloudsdkmoderation.v3.model.image_detection_result import ImageDetectionResult
from huaweicloudsdkmoderation.v3.model.image_detection_result_detail import ImageDetectionResultDetail
from huaweicloudsdkmoderation.v3.model.img_text_config import ImgTextConfig
from huaweicloudsdkmoderation.v3.model.ocr_text_detail import OCRTextDetail
from huaweicloudsdkmoderation.v3.model.qr_location_detail import QRLocationDetail
from huaweicloudsdkmoderation.v3.model.run_create_audio_moderation_job_request import RunCreateAudioModerationJobRequest
from huaweicloudsdkmoderation.v3.model.run_create_audio_moderation_job_response import RunCreateAudioModerationJobResponse
from huaweicloudsdkmoderation.v3.model.run_create_video_moderation_job_request import RunCreateVideoModerationJobRequest
from huaweicloudsdkmoderation.v3.model.run_create_video_moderation_job_response import RunCreateVideoModerationJobResponse
from huaweicloudsdkmoderation.v3.model.run_query_audio_moderation_job_request import RunQueryAudioModerationJobRequest
from huaweicloudsdkmoderation.v3.model.run_query_audio_moderation_job_response import RunQueryAudioModerationJobResponse
from huaweicloudsdkmoderation.v3.model.run_query_video_moderation_job_request import RunQueryVideoModerationJobRequest
from huaweicloudsdkmoderation.v3.model.run_query_video_moderation_job_response import RunQueryVideoModerationJobResponse
from huaweicloudsdkmoderation.v3.model.run_text_moderation_request import RunTextModerationRequest
from huaweicloudsdkmoderation.v3.model.run_text_moderation_response import RunTextModerationResponse
from huaweicloudsdkmoderation.v3.model.segment_result import SegmentResult
from huaweicloudsdkmoderation.v3.model.text_detection_data_req import TextDetectionDataReq
from huaweicloudsdkmoderation.v3.model.text_detection_req import TextDetectionReq
from huaweicloudsdkmoderation.v3.model.text_detection_result import TextDetectionResult
from huaweicloudsdkmoderation.v3.model.text_detection_result_detail import TextDetectionResultDetail
from huaweicloudsdkmoderation.v3.model.video_create_request import VideoCreateRequest
from huaweicloudsdkmoderation.v3.model.video_create_request_data import VideoCreateRequestData
from huaweicloudsdkmoderation.v3.model.video_moderation_audio_detail_list import VideoModerationAudioDetailList
from huaweicloudsdkmoderation.v3.model.video_moderation_detail_segment import VideoModerationDetailSegment
from huaweicloudsdkmoderation.v3.model.video_moderation_image_detail import VideoModerationImageDetail
from huaweicloudsdkmoderation.v3.model.video_moderation_image_detail_list import VideoModerationImageDetailList
from huaweicloudsdkmoderation.v3.model.video_moderation_image_detail_list_face_location import VideoModerationImageDetailListFaceLocation
from huaweicloudsdkmoderation.v3.model.video_moderation_image_detail_list_qr_location import VideoModerationImageDetailListQrLocation
from huaweicloudsdkmoderation.v3.model.video_moderation_result_request_params import VideoModerationResultRequestParams
from huaweicloudsdkmoderation.v3.model.video_moderation_result_request_params_data import VideoModerationResultRequestParamsData
from huaweicloudsdkmoderation.v3.model.video_moderation_result_result import VideoModerationResultResult
from huaweicloudsdkmoderation.v3.model.video_moderation_video_detail import VideoModerationVideoDetail

