name: Publish Check
permissions:
  contents: read
on:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Check
      run: |
        for dir in $(find . -type d -maxdepth 2 -mindepth 2 -name "huaweicloudsdk*" ! -name "huaweicloudsdkcore"); do
            pkg=$(basename "$dir")
            if ! grep -q "$pkg" huaweicloud-sdk-all/huaweicloudsdkall/requirements.txt; then
                echo "${pkg} not found in huaweicloud-sdk-all/huaweicloudsdkall/requirements.txt" >&2
                exit 1
            fi
        done
        version=$(cat VERSION)
        pip install huaweicloudsdkall=="$version"
      shell: bash
