name: Pytest CI Py33
on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'
jobs:
  build:  
    runs-on: ubuntu-18.04
    strategy:  
      matrix:  
        python-version: ['3.3', '3.4', '3.5']
    steps:  
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}  
      uses: actions/setup-python@v5
      with:  
        python-version: ${{ matrix.python-version }}  
    - name: Pytest CI
      run: |
        python -m pip install --upgrade pip
        cd huaweicloud-sdk-core || exit 1
        pip install -r test-requirements.txt
        ${{ vars.CI_CMD }}
